apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-todo-deployment
  labels:
    app: flask-todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-todo
  template:
    metadata:
      labels:
        app: flask-todo
    spec:
      containers:
      - name: flask-todo
        image: sharayu1418/flask-todo:latest
        ports:
        - containerPort: 5000
