apiVersion: v1
kind: ReplicationController
metadata:
  name: flask-todo-rc
spec:
  replicas: 2
  selector:
    app: flask-todo-rc
  template:
    metadata:
      labels:
        app: flask-todo-rc
    spec:
      containers:
      - name: flask-todo
        image: sharayu1418/flask-todo:latest
        ports:
        - containerPort: 5000
